### ISSUE TITLE
AXIS error Could not generate WSDL!

### ISSUE THREAD

**Issue by doubler84** [alaeessaki/spring-boot-axis1.4-server#1]
I started the Spring boot application but when i go to:

_http://localhost:8080/axis/services/Service?wsdl_

I don't see the wsdl but i see this error page by Axis:

> <html>
<body>

  | <h2>AXIS error</h2>
-- | --
  | <p>Could not generate WSDL!</p>
  | <p>There is no SOAP service at this location</p>
  |  

</body>
</html>

If I go to _http://localhost:8080/axis_ I see deployed services.

**Comment by doubler84** [comment]
I fixed that adding **/services/*** to the AxisServelt.

`@Bean
	public ServletRegistrationBean<AxisServlet> axisServlet() {
		AxisServlet servlet = new AxisServlet();
		return new ServletRegistrationBean<AxisServlet>(servlet, "/axis/*", "/services/*");
	}`

**Comment by alaeessaki** [comment]
Hello,
Can you please provide more informations about the issue. 
The wsdl url in default is `localhost:<port>/axis/<service-name>?wsdl` but you can always change this.

**Comment by doubler84** [comment]
- I cloned your repo
- started the spring boot app
- open browser and go to: http://localhost:8080/axis/Service?wsdl
- See what happen

**Comment by alaeessaki** [comment]
I've done exactly what you explained, but I didn't face any problem. The WSDL is successfully published in the expected link described in Readme: `localhost:<port>/axis/<service-name>?wsdl`, in this case : `http://localhost:8080/axis/Service?wsdl`.
What I've seen is that you were using the wrong URL, `http://localhost:8080/axis/services/Service?wsdl` instead of `http://localhost:8080/axis/Service?wsdl`.

But you can always change the URL, as you did in the bean configuration.

**Comment by doubler84** [comment]
ah... it works also http://localhost:8080/axis/Service?wsdl 
Sorry for the issue, have a nice day.

Thanks for this project about integration Spring + Axis

**Comment by alaeessaki** [comment]
No problem, if you have any other issues, feel free to open them and we'll discuss them.
Have a nice day.

**Comment by h1pmnh** [comment]
In case anyone else runs into this issue, the `And now... Some Services` page defaults to the `/services/<Service>?wsdl` and the suggested fix to add `/services/*` to the `WebServiceServerConfig` bean solves this problem. Not a huge deal but convenient if you're using the UI to get to the WSDL.

Thanks for putting this together, it's really helpful :)
